version: "3.9"


services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./bot/locales:/app/bot/locales
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      nats:
        condition: service_started

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    restart: always
#    ports:
#      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U user -d db'"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - "./postgres/data:/var/lib/postgresql/data"

  redis:
    image: redis:7.4.0
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data
    deploy:
      resources:
        limits:
          memory: 512M
#    ports:
#      - "6379:6379"
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30

  nats:
    image: nats:2.10.21
    entrypoint: /nats-server
    command: "-c /config/server.conf"
    restart: always
#    ports:
#      - "4222:4222"
#      - "8222:8222"
    volumes:
      - ./nats/data:/data
      - ./nats/config/server.conf:/config/server.conf

